// Canonical Subcontractor Contract for Services - bilingual EN/RO.
//
// Public, statically-laid-out at /legal/contract. No per-worker
// variation, no DB-stored signatures. Agreement formed by:
//   1. terms publicly accessible at a stable URL
//   2. acceptance clause printed on every payment advice
//   3. the sub accepting the payment
//
// Bilingual model:
//   - EN is the legally binding version. RO is a courtesy
//     translation rendered when the user's active locale is "ro".
//   - LegalContract.tsx shows a banner explaining the EN version
//     prevails for any dispute.
//   - Both copies stay structurally identical (same section numbers,
//     same paragraph count) so the rendering code doesn't need to
//     branch on locale beyond picking the array.
//
// Adding a clause: add it to BOTH _EN and _RO. The two arrays MUST
// stay parallel.

export interface ContractContext {
  contractorName: string;
  contractorRegNumber: string;
  contractorAddress: string;
  contractorSignatoryName: string;
  publicUrl: string;
}

export type Locale = "en" | "ro";

export interface SectionBlock {
  number: string;
  title: string;
  paragraphs: string[];
}

export interface RecitalBlock {
  letter: string;
  text: string;
}

// ---------- Acceptance clause (interpolated on payment advice + page) ----------

export function acceptanceClause(
  ctx: Pick<ContractContext, "contractorName" | "publicUrl">,
  locale: Locale = "en",
): string {
  if (locale === "ro") {
    return `Prin acceptarea acestei plăți și prin continuarea prestării serviciilor către ${ctx.contractorName} sau clienții acestuia, recunoști că ai avut posibilitatea de a consulta Contractul pentru Servicii disponibil la ${ctx.publicUrl} și ești de acord să fii obligat de termenii acestuia pentru toate serviciile prestate.`;
  }
  return `By accepting this payment, and by continuing to provide services to ${ctx.contractorName} or its clients, you acknowledge that you have had the opportunity to review the Contract for Services available at ${ctx.publicUrl}, and agree to be bound by its terms in respect of all services provided.`;
}

// ---------- EN: legally binding source ----------

const CONTRACT_SECTIONS_EN: SectionBlock[] = [
  {
    number: "1",
    title: "The Services",
    paragraphs: [
      "1.1 The Subcontractor will provide their nature of services to the Contractor. Due to the fluctuating nature of the work available the scope and extent of the services will be agreed verbally by the parties from time to time or will be confirmed in written schedules generated by the Contractor or otherwise furnished to the Subcontractor.",
      "1.2 The Subcontractor will ensure that the Services are provided to the standard expected by the Contractor and required by any governing legislation and regulations as well as complying with any standards agreed in writing from time to time between the parties.",
      "1.3 The Subcontractor will have discretion as to the methods used to provide the agreed Services whilst always ensuring that the relevant health and safety, regulatory, security and site timescales are complied with.",
      "1.4 The parties acknowledge that the Contractor shall not have the right (nor will the Contractor seek to) supervise, direct or control the manner in which the Subcontractor or the Delegates provide the Services.",
      "1.5 Due to the nature of the Services to be provided, the Subcontractor will provide the Services at the site or premises notified to the Subcontractor by the Contractor. Such site or premises is not the fixed place of business of the Subcontractor.",
      "1.6 The Subcontractor is responsible for the provision of the Services under this Contract. The Subcontractor agrees that he is legally responsible for the Services and for ensuring that the relevant insurance policies including public liability insurance are in place to cover the provision of Services. The Subcontractor agrees and accepts that, whilst the Contractor has insurance in place to cover its liability for the Contractor Services, this cover does not extend to covering the Subcontractor's liability for the Services.",
      "1.7 Unless agreed otherwise either verbally or in writing the Subcontractor is not required to provide major tools or equipment for the provision of the Services. The Subcontractor shall be responsible for the storage of his own materials and equipment.",
      "1.8 The Subcontractor is responsible for and bears the financial risk of rectification of any defective work or damage caused by the Subcontractor or the Subcontractor's Delegates. The Contractor will have sole discretion as to whether the Subcontractor rectifies the defective work or whether the Subcontractor is required to bear the cost of another party rectifying the defective work.",
      "1.9 Where the Subcontractor is required to bear the cost of any rectification then the Subcontractor agrees that the Contractor can deduct the cost of said rectification from any monies owed by the Contractor to the Subcontractor.",
      "1.10 The Contractor is not obliged to offer any work on any assignment to the Subcontractor at any time and the Subcontractor is not obliged to accept any work on any assignment at any time.",
      "1.11 Any offer of work by the Contractor does not in any way oblige the Contractor to offer further work or prevent the Contractor from withdrawing work already offered save for the Services as set out in Clause 1.1 in respect of which performance has commenced by the Subcontractor.",
      "1.12 The acceptance of any work by the Subcontractor does not oblige the Subcontractor to accept any further work or prevent the Subcontractor from withdrawing from work already accepted save for the Services as set out in Clause 1.1. This clause shall be without prejudice to Clauses 1.8 and 1.9 of this Agreement concerning rectification.",
      "1.13 The Subcontractor can provide services to other Contractors during the term of this Contract, including competitors of the Contractor, however the Subcontractor will not disclose any confidential information or trade secrets of the Contractor to any third party at any time.",
    ],
  },
  {
    number: "2",
    title: "Payment Terms",
    paragraphs: [
      "2.1 The parties agree that the Subcontractor is not obliged to submit tenders for work.",
      "2.2 The parties agree that the rate for the Services will be negotiated and verbally agreed from time to time.",
      "2.3 The parties agree that payments will be processed as follows:",
      "2.3.1 The commencement date referred to hereafter shall be the first day of the month following commencement of work on site.",
      "2.3.2 The first payment claim date shall be 30 days after the commencement date.",
      "2.3.3 Each subsequent payment claim date shall be 30 days after the date referred to in 2.3.2 above up to the date of substantial completion. Substantial completion consists of the date of completion of the works excluding any remedial and/or snagging works.",
      "2.3.4 The final payment claim date shall be 30 days after final completion. Final completion consists of the date the Subcontractor has completed all works including remedial and/or snagging works.",
      "2.3.5 In the instance the duration of the works is less than 45 days, the final payment claim date referred to at 2.3.4 above shall be replaced with 14 days after final completion.",
      "2.3.6 Payment will be made no later than 30 days after the payment claim dates referred to above.",
      "2.3.7 Interim payments shall be the difference between the aggregate of the gross value of works completed under the construction contract, less any deductions provided for in the construction, and the aggregate of interim payments that have already been made at that payment claim date.",
      "2.4 Costings of the work shall be the responsibility of the Subcontractor.",
      "2.5 The Contractor will provide the Subcontractor with a remittance statement in accordance with this Agreement and at a frequency agreed verbally from time to time and this shall act as a self-billed invoice.",
      "2.6 The Subcontractor agrees that as a self-employed subcontractor he has no entitlement to holiday pay, sick pay or any other payment during periods services are not provided including where the Services are cancelled by the Contractor.",
      "2.7 The parties agree that the Services are subject to the Relevant Contracts Tax (\"RCT\") system for tax purposes and that this contract is a 'relevant contract' for those purposes.",
      "2.8 The Subcontractor will upon request by the Contractor, without delay and in any event within 30 days, provide the Contractor with any information in his possession or control necessary to enable the Contractor to comply with its obligations as an RCT 'principal contractor'. The Subcontractor is responsible for ensuring that any information so provided is true and accurate and indemnifies the Contractor for any costs or losses incurred by the Contractor due to inaccurate or false information provided by the Subcontractor or any failure to provide the said information within 30 days of the Contractor's request.",
      "2.9 The Subcontractor shall be responsible for paying or discharging any taxes or charges as may be payable out of any monies paid to him under this contract, including in respect of Delegates.",
      "2.10 The Subcontractor is responsible for payment of expenses incurred in the course of his work.",
    ],
  },
  {
    number: "3",
    title: "Scope & Termination",
    paragraphs: [
      "3.1 Each separate retention of the Subcontractor (if any) shall be, unless otherwise agreed in writing, a separate and distinct contract to which each of these terms and conditions shall apply.",
      "3.2 The parties agree that the relationship between the parties is not one of employer and employee and that the Subcontractor is not a worker of the Contractor and consequently does not have the associated statutory rights. As a self-employed person in business on his own account, the Subcontractor agrees that he is responsible for making his own arrangements for preparing accounts and the payment of income tax and PRSI contributions as applicable.",
      "3.3 The Subcontractor is not an agent of the Contractor and has no authority, whether express, ostensible or implied, to bind the Contractor.",
      "3.4 The Subcontractor is not entitled to participate in the Contractor's grievance and disciplinary procedure, if any.",
      "3.5 This Contract may be immediately terminated by either party on notice to the other.",
      "3.6 This Contract is exclusively between the Contractor and the Subcontractor and does not represent or imply a contract between the Contractor and the Subcontractor's Delegates or between the Contractor's client and the Subcontractor or the Subcontractor's Delegates.",
    ],
  },
  {
    number: "4",
    title: "Health & Safety",
    paragraphs: [
      "4.1 The Subcontractor will ensure that it complies with all and any site operational rules relating to the operating times of the site, site security and site safety in accordance with the health and safety obligations of the Contractor and the site.",
      "4.2 Where the Services undertaken are specialised the Subcontractor warrants that it has the necessary clearances and licences to provide the Services. The Subcontractor will inform the Contractor immediately where these clearances or licences are revoked, rescinded, invalidated, suspended or not operational.",
    ],
  },
  {
    number: "5",
    title: "Subcontractor's Staff",
    paragraphs: [
      "5.1 The Subcontractor may send any Delegates to perform the Services. The Delegates may not be rejected by the Contractor save where in the reasonable opinion of the Contractor they do not possess the necessary skills or qualifications to carry out the Services.",
      "5.2 The Subcontractor will ensure that any Delegates have the necessary clearances and/or licences to provide the Services. The Subcontractor will notify the Contractor immediately where any of the said licences are revoked, rescinded, invalidated, suspended or not operational.",
      "5.3 Where Delegates are utilised by the Subcontractor there shall be no contractual or financial relationship between the Contractor and the Delegates. The Subcontractor is solely responsible for arranging payments to the Delegates that the Subcontractor engages to provide the Services.",
      "5.4 The Subcontractor is not entitled to any additional payments where the Subcontractor engages Delegates to provide the agreed Services.",
      "5.5 The Subcontractor is responsible for ensuring that the Contractor, or where more practically appropriate the site foreman, is informed of the fact that Delegates are to be sent to provide the Services in order to ensure that health and safety and on-site security measures are complied with.",
      "5.6 Where the Subcontractor utilises Delegates to provide the Services then the Subcontractor is responsible for the Services that the Delegates provide and is responsible for ensuring their compliance with these contractual terms. Furthermore, the Subcontractor agrees that it is responsible for and bears the financial risk of remedying any defective work carried out by any Delegates that the Subcontractor engages to provide the Services. The Subcontractor agrees that the Contractor has discretion as to how said defective work is remedied and that the costs of said remedy can be deducted from any monies that the Contractor owes the Subcontractor.",
      "5.7 The Subcontractor is responsible for any statutory payments including but not limited to holiday pay, sick pay and protected leave pay that may be due to any Delegates engaged by the Subcontractor to provide the Services and the Subcontractor agrees to indemnify the Contractor from any costs or losses resulting from any claims that any Delegates may make against the Contractor for said payments.",
      "5.8 The Subcontractor is responsible for how it engages any Delegates and is responsible for any tax and PRSI contributions due by any Delegates or by the Subcontractor. For the avoidance of doubt the deduction of tax and PRSI by the Contractor from payments made to the Subcontractor in no way creates or implies an obligation on the Contractor to administer or collect the tax and PRSI contributions of the Delegates.",
    ],
  },
  {
    number: "6",
    title: "Miscellaneous",
    paragraphs: [
      "6.1 The Subcontractor confirms that he has read and understood the terms and conditions herein and has been advised to take independent legal advice and any other professional advice he considers necessary before accepting any payment under or otherwise acting upon this Contract. The Subcontractor further confirms that he has been advised that his status as an independent contractor has implications for, inter alia, social welfare entitlements, employment law protections and personal taxation.",
      "6.2 Both parties agree this is intended to be and is a legally binding contract governing the nature of the contractual relationship between them. The Subcontractor acknowledges that by accepting any payment from the Contractor and by continuing to provide the Services to the Contractor or its clients, the Subcontractor accepts and is bound by these terms and conditions, which are published and available at samwisebc.com/legal/contract.",
      "6.3 Both parties agree that, with the exception of verbal agreements referred to in this Contract, these terms and conditions represent the whole agreement between them superseding all prior written and oral arrangements, understandings, representations, warranties and agreements (if any) between them.",
      "6.4 The Contractor may amend these terms from time to time by publishing the amended version at samwisebc.com/legal/contract; the Subcontractor's continued acceptance of payment and continued performance of the Services following publication constitutes acceptance of any such amendment. Any variation that adversely affects accrued rights of the Subcontractor in respect of Services already performed shall require the written agreement of both parties.",
      "6.5 The Headings used in the Contract are for ease of reference only and are not intended to be interpreted as part of the terms agreed between the parties. References to the masculine include the feminine.",
      "6.6 The parties agree that this contract is governed by the laws of Ireland and is subject to the exclusive jurisdiction of Ireland.",
    ],
  },
];

const RECITALS_EN: RecitalBlock[] = [
  { letter: "A", text: "The Contractor engages with Subcontractors for the provision of the Services (the \"Services\")." },
  { letter: "B", text: "These terms and conditions shall apply for each engagement unless varied, amended or otherwise agreed (whether verbally or otherwise) in accordance with the specific provisions of this contract." },
  { letter: "C", text: "Under these terms the Subcontractor has the right to use substitutes, subcontractor employees or hired assistants (the \"Delegates\") to provide the agreed services. The term Subcontractor in this contract is deemed to include any Delegates that the Subcontractor engages to provide the services." },
  { letter: "D", text: "The Subcontractor warrants that he has the skills, abilities, licences and clearances (whether provided by the Subcontractor or any Delegates) which may from time to time be available to the Contractor." },
  { letter: "E", text: "The Subcontractor is engaged in his own commercial undertaking and, subject to the terms of this contract, it is for him to decide how and when, subject to site operating hours, the work associated with it is carried out using sound management in the scheduling of engagements and the performance of tasks." },
];

const LEGALLY_BINDING_BANNER_EN = "The parties agree that they have read and understood the terms above and that they are a true reflection of the agreement between the parties and that both parties have had the opportunity to seek advice prior to the agreement of these terms. By continuing to provide services and by accepting payment under this contract the parties warrant that the contract in its entirety is true and reflects the actual agreement between the parties.";

// ---------- RO: courtesy translation ----------

const CONTRACT_SECTIONS_RO: SectionBlock[] = [
  {
    number: "1",
    title: "Serviciile",
    paragraphs: [
      "1.1 Subcontractorul va presta serviciile specifice activității sale către Contractor. Datorită naturii fluctuante a lucrărilor disponibile, sfera și amploarea serviciilor vor fi convenite verbal de către părți, periodic, sau vor fi confirmate în programe scrise emise de către Contractor sau furnizate în alt mod Subcontractorului.",
      "1.2 Subcontractorul se va asigura că Serviciile sunt prestate la standardul așteptat de Contractor și impus de orice legislație și reglementare aplicabilă, precum și că respectă orice standarde convenite în scris, periodic, între părți.",
      "1.3 Subcontractorul va avea libertatea de a alege metodele folosite pentru a presta Serviciile convenite, asigurându-se întotdeauna că sunt respectate cerințele relevante de sănătate și securitate, reglementare, securitate și termenele de șantier.",
      "1.4 Părțile recunosc că Contractorul nu va avea dreptul (și nu va încerca) să supervizeze, să direcționeze sau să controleze modul în care Subcontractorul sau Delegații prestează Serviciile.",
      "1.5 Datorită naturii Serviciilor de prestat, Subcontractorul va presta Serviciile la șantierul sau locația notificată de către Contractor. Acel șantier sau locație nu reprezintă sediul fix de activitate al Subcontractorului.",
      "1.6 Subcontractorul este responsabil pentru prestarea Serviciilor în baza acestui Contract. Subcontractorul este de acord că este răspunzător legal pentru Servicii și pentru asigurarea existenței polițelor de asigurare relevante, inclusiv asigurarea de răspundere civilă publică, care să acopere prestarea Serviciilor. Subcontractorul acceptă faptul că, deși Contractorul are asigurări care îi acoperă răspunderea pentru Serviciile Contractorului, această acoperire nu se extinde și asupra răspunderii Subcontractorului pentru Servicii.",
      "1.7 Cu excepția cazului în care s-a convenit altfel verbal sau în scris, Subcontractorul nu este obligat să furnizeze utilaje sau echipamente majore pentru prestarea Serviciilor. Subcontractorul va fi responsabil pentru depozitarea propriilor materiale și echipamente.",
      "1.8 Subcontractorul este responsabil și suportă riscul financiar al remedierii oricărei lucrări defectuoase sau a oricărei pagube cauzate de Subcontractor sau de Delegații Subcontractorului. Contractorul va avea libertatea de a decide dacă Subcontractorul remediază lucrarea defectuoasă sau dacă Subcontractorului i se cere să suporte costul remedierii de către o altă parte.",
      "1.9 Atunci când Subcontractorului i se cere să suporte costul oricărei remedieri, acesta este de acord ca Contractorul să poată deduce costul remedierii din orice sume datorate de Contractor Subcontractorului.",
      "1.10 Contractorul nu este obligat să ofere Subcontractorului lucrări la nicio misiune, în niciun moment, iar Subcontractorul nu este obligat să accepte lucrări la nicio misiune, în niciun moment.",
      "1.11 Orice ofertă de lucrare din partea Contractorului nu obligă Contractorul în vreun fel să ofere lucrări suplimentare și nici nu împiedică Contractorul să retragă lucrările deja oferite, cu excepția Serviciilor prevăzute la Clauza 1.1 pentru care prestarea a început deja.",
      "1.12 Acceptarea oricărei lucrări de către Subcontractor nu îl obligă să accepte lucrări suplimentare și nici nu îl împiedică să se retragă din lucrările deja acceptate, cu excepția Serviciilor prevăzute la Clauza 1.1. Această clauză nu aduce atingere Clauzelor 1.8 și 1.9 din prezentul Acord privind remedierea.",
      "1.13 Subcontractorul poate presta servicii și altor Contractori pe durata acestui Contract, inclusiv concurenți ai Contractorului; cu toate acestea, Subcontractorul nu va divulga niciodată unei terțe părți informații confidențiale sau secrete comerciale ale Contractorului.",
    ],
  },
  {
    number: "2",
    title: "Termeni de plată",
    paragraphs: [
      "2.1 Părțile convin că Subcontractorul nu este obligat să depună oferte pentru lucrări.",
      "2.2 Părțile convin că tariful pentru Servicii va fi negociat și convenit verbal, periodic.",
      "2.3 Părțile convin că plățile vor fi procesate astfel:",
      "2.3.1 Data începerii la care se face referire mai jos va fi prima zi a lunii ce urmează începerii lucrărilor pe șantier.",
      "2.3.2 Prima dată de solicitare a plății va fi la 30 de zile după data începerii.",
      "2.3.3 Fiecare dată ulterioară de solicitare a plății va fi la 30 de zile după data prevăzută la 2.3.2 de mai sus, până la data finalizării substanțiale. Finalizarea substanțială reprezintă data finalizării lucrărilor, excluzând orice lucrări de remediere și/sau de snagging.",
      "2.3.4 Data finală de solicitare a plății va fi la 30 de zile după finalizarea finală. Finalizarea finală reprezintă data la care Subcontractorul a finalizat toate lucrările, inclusiv lucrările de remediere și/sau snagging.",
      "2.3.5 În cazul în care durata lucrărilor este mai mică de 45 de zile, data finală de solicitare a plății prevăzută la 2.3.4 de mai sus va fi înlocuită cu 14 zile după finalizarea finală.",
      "2.3.6 Plata va fi efectuată în cel mult 30 de zile după datele de solicitare a plății menționate mai sus.",
      "2.3.7 Plățile intermediare vor reprezenta diferența dintre valoarea brută cumulată a lucrărilor finalizate în baza contractului de construcții, minus orice deduceri prevăzute în construcție, și totalul plăților intermediare deja efectuate la acea dată de solicitare a plății.",
      "2.4 Calculul costurilor lucrării va fi în responsabilitatea Subcontractorului.",
      "2.5 Contractorul va furniza Subcontractorului un extras de remitere conform acestui Acord și cu o frecvență agreată verbal, periodic, iar acesta va funcționa ca o factură self-billed (auto-emisă).",
      "2.6 Subcontractorul recunoaște că, în calitate de subcontractor independent (self-employed), nu are dreptul la plata concediului, plata concediului medical sau orice altă plată în perioadele în care nu prestează servicii, inclusiv atunci când Serviciile sunt anulate de Contractor.",
      "2.7 Părțile convin că Serviciile fac obiectul regimului fiscal Relevant Contracts Tax (\"RCT\") și că acest contract este un 'relevant contract' în acest sens.",
      "2.8 La cererea Contractorului, Subcontractorul va furniza fără întârziere și în orice caz în termen de 30 de zile orice informație aflată în posesia sau controlul său, necesară pentru ca Contractorul să își îndeplinească obligațiile de 'principal contractor' RCT. Subcontractorul este responsabil să se asigure că informațiile furnizate sunt adevărate și exacte și îl despăgubește pe Contractor pentru orice costuri sau pierderi suferite ca urmare a unor informații inexacte sau false furnizate de Subcontractor sau a neîndeplinirii furnizării respectivelor informații în termen de 30 de zile de la cererea Contractorului.",
      "2.9 Subcontractorul va fi responsabil pentru plata sau achitarea oricăror taxe sau impozite datorate din sumele care i se plătesc în baza acestui contract, inclusiv în ceea ce privește Delegații.",
      "2.10 Subcontractorul este responsabil pentru plata cheltuielilor suportate în cursul lucrărilor sale.",
    ],
  },
  {
    number: "3",
    title: "Sfera contractului și încetare",
    paragraphs: [
      "3.1 Fiecare angajament separat al Subcontractorului (dacă există) va constitui, cu excepția cazului în care se convine altfel în scris, un contract separat și distinct căruia i se aplică acești termeni și condiții.",
      "3.2 Părțile convin că relația dintre ele nu este una de angajator și angajat și că Subcontractorul nu este un lucrător al Contractorului și, în consecință, nu are drepturile statutare asociate. În calitate de persoană care desfășoară activități independente pe cont propriu, Subcontractorul este de acord că este responsabil pentru propriile demersuri privind ținerea contabilității și plata impozitului pe venit și a contribuțiilor PRSI, după caz.",
      "3.3 Subcontractorul nu este agent al Contractorului și nu are autoritatea, expresă, aparentă sau implicită, de a obliga Contractorul.",
      "3.4 Subcontractorul nu are dreptul să participe la procedura de plângere și disciplinară a Contractorului, dacă există.",
      "3.5 Acest Contract poate fi reziliat imediat de oricare parte prin notificarea celeilalte.",
      "3.6 Acest Contract este exclusiv între Contractor și Subcontractor și nu reprezintă sau implică un contract între Contractor și Delegații Subcontractorului sau între clientul Contractorului și Subcontractor sau Delegații Subcontractorului.",
    ],
  },
  {
    number: "4",
    title: "Sănătate și securitate",
    paragraphs: [
      "4.1 Subcontractorul se va asigura că respectă toate regulile operaționale ale șantierului privind programul de lucru al șantierului, securitatea șantierului și siguranța șantierului, în conformitate cu obligațiile de sănătate și securitate ale Contractorului și ale șantierului.",
      "4.2 Atunci când Serviciile prestate sunt specializate, Subcontractorul garantează că deține autorizările și licențele necesare pentru prestarea Serviciilor. Subcontractorul va informa imediat Contractorul în cazul în care aceste autorizări sau licențe sunt revocate, anulate, invalidate, suspendate sau nu mai sunt operaționale.",
    ],
  },
  {
    number: "5",
    title: "Personalul Subcontractorului",
    paragraphs: [
      "5.1 Subcontractorul poate trimite Delegați pentru a presta Serviciile. Delegații nu pot fi respinși de Contractor, cu excepția cazului în care, în opinia rezonabilă a Contractorului, aceștia nu au competențele sau calificările necesare pentru a presta Serviciile.",
      "5.2 Subcontractorul se va asigura că Delegații dețin autorizările și/sau licențele necesare pentru prestarea Serviciilor. Subcontractorul va notifica imediat Contractorul în cazul în care vreuna dintre licențele menționate este revocată, anulată, invalidată, suspendată sau nu mai este operațională.",
      "5.3 Atunci când Subcontractorul folosește Delegați, nu există nicio relație contractuală sau financiară între Contractor și Delegați. Subcontractorul este singurul responsabil pentru efectuarea plăților către Delegații pe care îi angajează pentru prestarea Serviciilor.",
      "5.4 Subcontractorul nu are dreptul la plăți suplimentare atunci când angajează Delegați pentru a presta Serviciile convenite.",
      "5.5 Subcontractorul este responsabil pentru informarea Contractorului sau, atunci când este mai practic, a șefului de șantier, despre faptul că vor fi trimiși Delegați pentru a presta Serviciile, pentru a asigura respectarea măsurilor de sănătate, securitate și a măsurilor de securitate pe șantier.",
      "5.6 Atunci când Subcontractorul folosește Delegați pentru a presta Serviciile, Subcontractorul este responsabil pentru Serviciile prestate de Delegați și pentru asigurarea respectării de către aceștia a acestor termeni contractuali. Mai mult, Subcontractorul este de acord că este responsabil și suportă riscul financiar al remedierii oricărei lucrări defectuoase realizate de orice Delegat pe care îl angajează pentru prestarea Serviciilor. Subcontractorul este de acord ca Contractorul să decidă modul în care se remediază lucrarea defectuoasă și ca costurile remedierii să poată fi deduse din orice sume datorate de Contractor Subcontractorului.",
      "5.7 Subcontractorul este responsabil pentru orice plăți statutare, inclusiv, fără limitare, indemnizația de concediu, indemnizația de concediu medical și indemnizația de concediu protejat, datorate Delegaților angajați de Subcontractor pentru prestarea Serviciilor, iar Subcontractorul îl despăgubește pe Contractor pentru orice costuri sau pierderi rezultate din eventuale pretenții ale Delegaților împotriva Contractorului pentru aceste plăți.",
      "5.8 Subcontractorul este responsabil pentru modul în care angajează Delegații și este responsabil pentru orice impozite și contribuții PRSI datorate de Delegați sau de Subcontractor. Pentru evitarea oricărui dubiu, deducerea de impozite și PRSI de către Contractor din plățile efectuate către Subcontractor nu creează și nu implică nicio obligație a Contractorului de a administra sau colecta impozitele și contribuțiile PRSI ale Delegaților.",
    ],
  },
  {
    number: "6",
    title: "Diverse",
    paragraphs: [
      "6.1 Subcontractorul confirmă că a citit și înțeles termenii și condițiile prezente și că i s-a recomandat să obțină consultanță juridică independentă și orice altă consultanță profesională pe care o consideră necesară înainte de a accepta orice plată sau de a acționa în temeiul acestui Contract. Subcontractorul confirmă, de asemenea, că a fost informat că statutul său de contractor independent are implicații, printre altele, asupra drepturilor de asigurări sociale, protecțiilor din dreptul muncii și fiscalității personale.",
      "6.2 Ambele părți convin că aceasta reprezintă și este destinată să fie un contract obligatoriu din punct de vedere juridic, care guvernează natura relației contractuale dintre ele. Subcontractorul recunoaște că, prin acceptarea oricărei plăți de la Contractor și prin continuarea prestării Serviciilor către Contractor sau clienții acestuia, Subcontractorul acceptă și este obligat de acești termeni și condiții, care sunt publicate și disponibile la samwisebc.com/legal/contract.",
      "6.3 Ambele părți convin că, cu excepția acordurilor verbale menționate în acest Contract, acești termeni și condiții reprezintă întregul acord dintre ele, înlocuind toate aranjamentele, înțelegerile, reprezentările, garanțiile și acordurile anterioare scrise sau verbale (dacă există) dintre ele.",
      "6.4 Contractorul poate modifica acești termeni periodic, publicând versiunea modificată la samwisebc.com/legal/contract; continuarea acceptării plăților și continuarea prestării Serviciilor de către Subcontractor după publicare constituie acceptarea oricărei astfel de modificări. Orice modificare care afectează negativ drepturile deja dobândite ale Subcontractorului în legătură cu Serviciile deja prestate va necesita acordul scris al ambelor părți.",
      "6.5 Titlurile folosite în Contract sunt doar pentru ușurința referinței și nu sunt destinate să fie interpretate ca parte din termenii conveniți între părți. Referințele la genul masculin includ și genul feminin.",
      "6.6 Părțile convin că acest contract este guvernat de legile Irlandei și este supus jurisdicției exclusive a Irlandei.",
    ],
  },
];

const RECITALS_RO: RecitalBlock[] = [
  { letter: "A", text: "Contractorul colaborează cu Subcontractori pentru prestarea Serviciilor (\"Serviciile\")." },
  { letter: "B", text: "Acești termeni și condiții se vor aplica fiecărui angajament, cu excepția cazului în care sunt modificați, amendați sau s-a convenit altfel (verbal sau în alt mod) în conformitate cu prevederile specifice ale acestui contract." },
  { letter: "C", text: "În baza acestor termeni, Subcontractorul are dreptul de a folosi înlocuitori, angajați ai subcontractorului sau asistenți angajați (\"Delegații\") pentru prestarea serviciilor convenite. Termenul Subcontractor din acest contract este considerat a include orice Delegați pe care Subcontractorul îi angajează pentru prestarea serviciilor." },
  { letter: "D", text: "Subcontractorul garantează că deține competențele, abilitățile, licențele și autorizările (furnizate fie de Subcontractor, fie de orice Delegați) care pot fi disponibile periodic Contractorului." },
  { letter: "E", text: "Subcontractorul desfășoară propria sa activitate comercială și, sub rezerva termenilor acestui contract, îi revine lui să decidă cum și când, sub rezerva orelor de funcționare a șantierului, se realizează lucrarea asociată acestuia, folosind un management adecvat în programarea angajamentelor și executarea sarcinilor." },
];

const LEGALLY_BINDING_BANNER_RO = "Părțile convin că au citit și înțeles termenii de mai sus și că aceștia reflectă cu acuratețe acordul dintre părți și că ambele părți au avut posibilitatea de a solicita consultanță înainte de acordul asupra acestor termeni. Prin continuarea prestării serviciilor și prin acceptarea plății în baza acestui contract, părțile garantează că contractul în întregime este real și reflectă acordul efectiv dintre părți.";

// ---------- Locale dispatch ----------

export function contractSections(locale: Locale): SectionBlock[] {
  return locale === "ro" ? CONTRACT_SECTIONS_RO : CONTRACT_SECTIONS_EN;
}

export function recitals(locale: Locale): RecitalBlock[] {
  return locale === "ro" ? RECITALS_RO : RECITALS_EN;
}

export function legallyBindingBanner(locale: Locale): string {
  return locale === "ro" ? LEGALLY_BINDING_BANNER_RO : LEGALLY_BINDING_BANNER_EN;
}

// Back-compat exports for any caller that still imports the EN
// constants directly (e.g. PDF generator that we haven't localised
// yet). Keep these aliased to EN so PDFs stay legally binding.
export const CONTRACT_SECTIONS = CONTRACT_SECTIONS_EN;
export const RECITALS = RECITALS_EN;
export const LEGALLY_BINDING_BANNER = LEGALLY_BINDING_BANNER_EN;
