// Canonical Subcontractor Contract for Services.
//
// This is the same text every sub is bound to. We render it as a
// public, statically-laid-out document at /legal/contract; no
// per-worker variation in the body, no DB-stored signatures. The
// agreement is established by:
//
//   1. The terms being publicly accessible at a stable URL
//   2. The acceptance clause printed on every payment advice the sub
//      receives (see ACCEPTANCE_CLAUSE below)
//   3. The sub accepting the payment (cash flow = implicit agreement)
//
// Structure mirrors the Enagh reference document the user provided:
// preamble + recitals A-E + 6 numbered sections + legally-binding
// banner + two-column signature footer.

export interface ContractContext {
  // BC's identity. Hard-coded from app_settings on the page that
  // renders the contract.
  contractorName: string;        // e.g. "Samwise Building Contractors Ltd"
  contractorRegNumber: string;   // e.g. "575739"
  contractorAddress: string;     // full address
  contractorSignatoryName: string; // e.g. "JP Donnelly"
  // Public URL of this contract (used in the body where it
  // self-references, and in the acceptance clause below).
  publicUrl: string;
}

// The canonical acceptance clause the user specified verbatim. We
// interpolate {contractorName} + {publicUrl} but otherwise the wording
// is fixed.
export function acceptanceClause(ctx: Pick<ContractContext, "contractorName" | "publicUrl">): string {
  return `By accepting this payment, and by continuing to provide services to ${ctx.contractorName} or its clients, you acknowledge that you have had the opportunity to review the Contract for Services available at ${ctx.publicUrl}, and agree to be bound by its terms in respect of all services provided.`;
}

// Section structure. Renderer maps over this and renders each section
// with proper hierarchical numbering. Body text is the user's
// reference document with one tweak: "the Contractor" / "the
// Subcontractor" stay generic so the same body works for every reader.
export const CONTRACT_SECTIONS: Array<{
  number: string;
  title: string;
  paragraphs: string[];
}> = [
  {
    number: "1",
    title: "The Services",
    paragraphs: [
      "1.1 The Subcontractor will provide their nature of services to the Contractor. Due to the fluctuating nature of the work available the scope and extent of the services will be agreed verbally by the parties from time to time or will be confirmed in written schedules generated by the Contractor or otherwise furnished to the Subcontractor.",
      "1.2 The Subcontractor will ensure that the Services are provided to the standard expected by the Contractor and required by any governing legislation and regulations as well as complying with any standards agreed in writing from time to time between the parties.",
      "1.3 The Subcontractor will have discretion as to the methods used to provide the agreed Services whilst always ensuring that the relevant health and safety, regulatory, security and site timescales are complied with.",
      "1.4 The parties acknowledge that the Contractor shall not have the right (nor will the Contractor seek to) supervise, direct or control the manner in which the Subcontractor or the Delegates provide the Services.",
      "1.5 Due to the nature of the Services to be provided, the Subcontractor will provide the Services at the site or premises notified to the Subcontractor by the Contractor. Such site or premises is not the fixed place of business of the Subcontractor.",
      "1.6 The Subcontractor is responsible for the provision of the Services under this Contract. The Subcontractor agrees that he is legally responsible for the Services and for ensuring that the relevant insurance policies including public liability insurance are in place to cover the provision of Services. The Subcontractor agrees and accepts that, whilst the Contractor has insurance in place to cover its liability for the Contractor Services, this cover does not extend to covering the Subcontractor's liability for the Services.",
      "1.7 Unless agreed otherwise either verbally or in writing the Subcontractor is not required to provide major tools or equipment for the provision of the Services. The Subcontractor shall be responsible for the storage of his own materials and equipment.",
      "1.8 The Subcontractor is responsible for and bears the financial risk of rectification of any defective work or damage caused by the Subcontractor or the Subcontractor's Delegates. The Contractor will have sole discretion as to whether the Subcontractor rectifies the defective work or whether the Subcontractor is required to bear the cost of another party rectifying the defective work.",
      "1.9 Where the Subcontractor is required to bear the cost of any rectification then the Subcontractor agrees that the Contractor can deduct the cost of said rectification from any monies owed by the Contractor to the Subcontractor.",
      "1.10 The Contractor is not obliged to offer any work on any assignment to the Subcontractor at any time and the Subcontractor is not obliged to accept any work on any assignment at any time.",
      "1.11 Any offer of work by the Contractor does not in any way oblige the Contractor to offer further work or prevent the Contractor from withdrawing work already offered save for the Services as set out in Clause 1.1 in respect of which performance has commenced by the Subcontractor.",
      "1.12 The acceptance of any work by the Subcontractor does not oblige the Subcontractor to accept any further work or prevent the Subcontractor from withdrawing from work already accepted save for the Services as set out in Clause 1.1. This clause shall be without prejudice to Clauses 1.8 and 1.9 of this Agreement concerning rectification.",
      "1.13 The Subcontractor can provide services to other Contractors during the term of this Contract, including competitors of the Contractor, however the Subcontractor will not disclose any confidential information or trade secrets of the Contractor to any third party at any time.",
    ],
  },
  {
    number: "2",
    title: "Payment Terms",
    paragraphs: [
      "2.1 The parties agree that the Subcontractor is not obliged to submit tenders for work.",
      "2.2 The parties agree that the rate for the Services will be negotiated and verbally agreed from time to time.",
      "2.3 The parties agree that payments will be processed as follows:",
      "2.3.1 The commencement date referred to hereafter shall be the first day of the month following commencement of work on site.",
      "2.3.2 The first payment claim date shall be 30 days after the commencement date.",
      "2.3.3 Each subsequent payment claim date shall be 30 days after the date referred to in 2.3.2 above up to the date of substantial completion. Substantial completion consists of the date of completion of the works excluding any remedial and/or snagging works.",
      "2.3.4 The final payment claim date shall be 30 days after final completion. Final completion consists of the date the Subcontractor has completed all works including remedial and/or snagging works.",
      "2.3.5 In the instance the duration of the works is less than 45 days, the final payment claim date referred to at 2.3.4 above shall be replaced with 14 days after final completion.",
      "2.3.6 Payment will be made no later than 30 days after the payment claim dates referred to above.",
      "2.3.7 Interim payments shall be the difference between the aggregate of the gross value of works completed under the construction contract, less any deductions provided for in the construction, and the aggregate of interim payments that have already been made at that payment claim date.",
      "2.4 Costings of the work shall be the responsibility of the Subcontractor.",
      "2.5 The Contractor will provide the Subcontractor with a remittance statement in accordance with this Agreement and at a frequency agreed verbally from time to time and this shall act as a self-billed invoice.",
      "2.6 The Subcontractor agrees that as a self-employed subcontractor he has no entitlement to holiday pay, sick pay or any other payment during periods services are not provided including where the Services are cancelled by the Contractor.",
      "2.7 The parties agree that the Services are subject to the Relevant Contracts Tax (\"RCT\") system for tax purposes and that this contract is a 'relevant contract' for those purposes.",
      "2.8 The Subcontractor will upon request by the Contractor, without delay and in any event within 30 days, provide the Contractor with any information in his possession or control necessary to enable the Contractor to comply with its obligations as an RCT 'principal contractor'. The Subcontractor is responsible for ensuring that any information so provided is true and accurate and indemnifies the Contractor for any costs or losses incurred by the Contractor due to inaccurate or false information provided by the Subcontractor or any failure to provide the said information within 30 days of the Contractor's request.",
      "2.9 The Subcontractor shall be responsible for paying or discharging any taxes or charges as may be payable out of any monies paid to him under this contract, including in respect of Delegates.",
      "2.10 The Subcontractor is responsible for payment of expenses incurred in the course of his work.",
    ],
  },
  {
    number: "3",
    title: "Scope & Termination",
    paragraphs: [
      "3.1 Each separate retention of the Subcontractor (if any) shall be, unless otherwise agreed in writing, a separate and distinct contract to which each of these terms and conditions shall apply.",
      "3.2 The parties agree that the relationship between the parties is not one of employer and employee and that the Subcontractor is not a worker of the Contractor and consequently does not have the associated statutory rights. As a self-employed person in business on his own account, the Subcontractor agrees that he is responsible for making his own arrangements for preparing accounts and the payment of income tax and PRSI contributions as applicable.",
      "3.3 The Subcontractor is not an agent of the Contractor and has no authority, whether express, ostensible or implied, to bind the Contractor.",
      "3.4 The Subcontractor is not entitled to participate in the Contractor's grievance and disciplinary procedure, if any.",
      "3.5 This Contract may be immediately terminated by either party on notice to the other.",
      "3.6 This Contract is exclusively between the Contractor and the Subcontractor and does not represent or imply a contract between the Contractor and the Subcontractor's Delegates or between the Contractor's client and the Subcontractor or the Subcontractor's Delegates.",
    ],
  },
  {
    number: "4",
    title: "Health & Safety",
    paragraphs: [
      "4.1 The Subcontractor will ensure that it complies with all and any site operational rules relating to the operating times of the site, site security and site safety in accordance with the health and safety obligations of the Contractor and the site.",
      "4.2 Where the Services undertaken are specialised the Subcontractor warrants that it has the necessary clearances and licences to provide the Services. The Subcontractor will inform the Contractor immediately where these clearances or licences are revoked, rescinded, invalidated, suspended or not operational.",
    ],
  },
  {
    number: "5",
    title: "Subcontractor's Staff",
    paragraphs: [
      "5.1 The Subcontractor may send any Delegates to perform the Services. The Delegates may not be rejected by the Contractor save where in the reasonable opinion of the Contractor they do not possess the necessary skills or qualifications to carry out the Services.",
      "5.2 The Subcontractor will ensure that any Delegates have the necessary clearances and/or licences to provide the Services. The Subcontractor will notify the Contractor immediately where any of the said licences are revoked, rescinded, invalidated, suspended or not operational.",
      "5.3 Where Delegates are utilised by the Subcontractor there shall be no contractual or financial relationship between the Contractor and the Delegates. The Subcontractor is solely responsible for arranging payments to the Delegates that the Subcontractor engages to provide the Services.",
      "5.4 The Subcontractor is not entitled to any additional payments where the Subcontractor engages Delegates to provide the agreed Services.",
      "5.5 The Subcontractor is responsible for ensuring that the Contractor, or where more practically appropriate the site foreman, is informed of the fact that Delegates are to be sent to provide the Services in order to ensure that health and safety and on-site security measures are complied with.",
      "5.6 Where the Subcontractor utilises Delegates to provide the Services then the Subcontractor is responsible for the Services that the Delegates provide and is responsible for ensuring their compliance with these contractual terms. Furthermore, the Subcontractor agrees that it is responsible for and bears the financial risk of remedying any defective work carried out by any Delegates that the Subcontractor engages to provide the Services. The Subcontractor agrees that the Contractor has discretion as to how said defective work is remedied and that the costs of said remedy can be deducted from any monies that the Contractor owes the Subcontractor.",
      "5.7 The Subcontractor is responsible for any statutory payments including but not limited to holiday pay, sick pay and protected leave pay that may be due to any Delegates engaged by the Subcontractor to provide the Services and the Subcontractor agrees to indemnify the Contractor from any costs or losses resulting from any claims that any Delegates may make against the Contractor for said payments.",
      "5.8 The Subcontractor is responsible for how it engages any Delegates and is responsible for any tax and PRSI contributions due by any Delegates or by the Subcontractor. For the avoidance of doubt the deduction of tax and PRSI by the Contractor from payments made to the Subcontractor in no way creates or implies an obligation on the Contractor to administer or collect the tax and PRSI contributions of the Delegates.",
    ],
  },
  {
    number: "6",
    title: "Miscellaneous",
    paragraphs: [
      "6.1 The Subcontractor confirms that he has read and understood the terms and conditions herein and has been advised to take independent legal advice and any other professional advice he considers necessary before signing. The Subcontractor further confirms that he has been advised that his status as an independent contractor has implications for, inter alia, social welfare entitlements, employment law protections and personal taxation.",
      "6.2 Both parties agree this is intended to be and is a legally binding contract governing the nature of the contractual relationship between them.",
      "6.3 Both parties agree that, with the exception of verbal agreements referred to in this Contract, these terms and conditions represent the whole agreement between them superseding all prior written and oral arrangements, understandings, representations, warranties and agreements (if any) between them.",
      "6.4 No variations may be made to these terms unless agreed in writing and signed by both parties.",
      "6.5 The Headings used in the Contract are for ease of reference only and are not intended to be interpreted as part of the terms agreed between the parties. References to the masculine include the feminine.",
      "6.6 The parties agree that this contract is governed by the laws of Ireland and is subject to the exclusive jurisdiction of Ireland.",
    ],
  },
];

export const RECITALS: Array<{ letter: string; text: string }> = [
  { letter: "A", text: "The Contractor engages with Subcontractors for the provision of the Services (the \"Services\")." },
  { letter: "B", text: "These terms and conditions shall apply for each engagement unless varied, amended or otherwise agreed (whether verbally or otherwise) in accordance with the specific provisions of this contract." },
  { letter: "C", text: "Under these terms the Subcontractor has the right to use substitutes, subcontractor employees or hired assistants (the \"Delegates\") to provide the agreed services. The term Subcontractor in this contract is deemed to include any Delegates that the Subcontractor engages to provide the services." },
  { letter: "D", text: "The Subcontractor warrants that he has the skills, abilities, licences and clearances (whether provided by the Subcontractor or any Delegates) which may from time to time be available to the Contractor." },
  { letter: "E", text: "The Subcontractor is engaged in his own commercial undertaking and, subject to the terms of this contract, it is for him to decide how and when, subject to site operating hours, the work associated with it is carried out using sound management in the scheduling of engagements and the performance of tasks." },
];

export const LEGALLY_BINDING_BANNER = "The parties agree that they have read and understood the terms above and that they are a true reflection of the agreement between the parties and that both parties have had the opportunity to seek advice prior to the agreement of these terms. By continuing to provide services and by accepting payment under this contract the parties warrant that the contract in its entirety is true and reflects the actual agreement between the parties.";
