// Self-billing invoice PDF generator. Pure client-side: takes the invoice
// JSON returned by GET /admin/subcontractors/:id/invoice and produces a
// downloadable PDF using jsPDF + jspdf-autotable. No server roundtrip.

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { InvoicePayload } from "./types";

function fmtMoneyMinor(amountMinor: number, currency: string): string {
  try {
    return new Intl.NumberFormat("en-IE", {
      style: "currency",
      currency,
    }).format(amountMinor / 100);
  } catch {
    return `${currency} ${(amountMinor / 100).toFixed(2)}`;
  }
}

function fmtDate(s: string | null | undefined): string {
  if (!s) return "—";
  try {
    return new Date(s).toLocaleDateString("en-IE", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  } catch {
    return s;
  }
}

export function generateInvoicePdf(inv: InvoicePayload, brandName = "Samwise"): jsPDF {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // ---- Header bar ----
  doc.setFillColor(15, 23, 34); // ink-900
  doc.rect(0, 0, pageWidth, 80, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Self-billing invoice", margin, 38);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(180, 188, 204);
  doc.text(`Generated by ${brandName}`, margin, 56);
  doc.setTextColor(245, 158, 11); // accent
  doc.text(inv.invoiceNumber, pageWidth - margin, 38, { align: "right" });
  doc.setTextColor(180, 188, 204);
  doc.text(
    `Issued ${new Date(inv.issuedAt).toLocaleDateString("en-IE")}`,
    pageWidth - margin,
    56,
    { align: "right" },
  );

  // ---- Parties ----
  let y = 110;
  doc.setTextColor(80, 80, 80);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("FROM (PRINCIPAL CONTRACTOR)", margin, y);
  doc.text("TO (SUBCONTRACTOR)", pageWidth / 2 + 10, y);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(10);
  y += 14;

  const principalLines = [
    inv.principal.name || "[Set principal name in Settings]",
    inv.principal.address || "",
    inv.principal.vat ? `VAT: ${inv.principal.vat}` : "",
    inv.principal.email || "",
  ].filter(Boolean);

  const subLines = [
    inv.subcontractor.fullName || "—",
    [inv.subcontractor.address1, inv.subcontractor.address2].filter(Boolean).join(", "),
    [inv.subcontractor.town, inv.subcontractor.postcode].filter(Boolean).join(" "),
    inv.subcontractor.email || "",
    inv.subcontractor.ppsNumber ? `PPS: ${inv.subcontractor.ppsNumber}` : "",
    inv.subcontractor.vatNumber ? `VAT: ${inv.subcontractor.vatNumber}` : "",
  ].filter(Boolean);

  const colW = pageWidth / 2 - margin - 10;
  const fromTextLines: string[] = [];
  for (const ln of principalLines) {
    fromTextLines.push(...doc.splitTextToSize(ln, colW));
  }
  const toTextLines: string[] = [];
  for (const ln of subLines) {
    toTextLines.push(...doc.splitTextToSize(ln, colW));
  }
  fromTextLines.forEach((ln, i) => doc.text(ln, margin, y + i * 13));
  toTextLines.forEach((ln, i) => doc.text(ln, pageWidth / 2 + 10, y + i * 13));

  const blockH = Math.max(fromTextLines.length, toTextLines.length) * 13;
  y += blockH + 24;

  // ---- Period / RCT badge ----
  doc.setFillColor(247, 248, 250); // ink-50
  doc.roundedRect(margin, y, pageWidth - margin * 2, 40, 4, 4, "F");
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.setFont("helvetica", "bold");
  doc.text("PERIOD", margin + 12, y + 16);
  doc.text("RCT RATE", margin + 200, y + 16);
  doc.text("VAT", margin + 320, y + 16);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(11);
  doc.text(
    `${fmtDate(inv.period.from)} – ${fmtDate(inv.period.to)}`,
    margin + 12,
    y + 32,
  );
  doc.text(
    inv.subcontractor.rctRate ? `${inv.subcontractor.rctRate}%` : "N/A",
    margin + 200,
    y + 32,
  );
  doc.text(
    inv.subcontractor.vatReverseCharge ? "Reverse charge" : "Standard",
    margin + 320,
    y + 32,
  );
  y += 60;

  // ---- Line items table ----
  const head = [["Date", "Period", "Hours", "Reference", "Site", "RCT", "Gross", "Net"]];
  const body = inv.lines.map((p) => [
    fmtDate(p.paymentDate),
    p.periodStart && p.periodEnd ? `${fmtDate(p.periodStart)} – ${fmtDate(p.periodEnd)}` : "—",
    p.hours != null ? p.hours.toFixed(2) : "—",
    p.reference || "—",
    p.siteRef || "—",
    p.rctRate ? `-${fmtMoneyMinor(p.rctDeductionMinor, p.currency)} (${p.rctRate}%)` : "—",
    fmtMoneyMinor(p.grossMinor, p.currency),
    fmtMoneyMinor(p.netMinor, p.currency),
  ]);

  autoTable(doc, {
    head,
    body,
    startY: y,
    margin: { left: margin, right: margin },
    theme: "grid",
    headStyles: {
      fillColor: [15, 23, 34],
      textColor: 255,
      fontStyle: "bold",
      fontSize: 9,
    },
    styles: { fontSize: 9, cellPadding: 6 },
    columnStyles: {
      2: { halign: "right" },
      5: { halign: "right" },
      6: { halign: "right", fontStyle: "bold" },
      7: { halign: "right", fontStyle: "bold" },
    },
  });

  // @ts-expect-error autoTable mutates internal lastAutoTable
  let afterTableY: number = doc.lastAutoTable?.finalY ?? y + 20;
  afterTableY += 18;

  // ---- Totals ----
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(80, 80, 80);
  doc.text("TOTALS", margin, afterTableY);
  afterTableY += 6;

  for (const [currency, t] of Object.entries(inv.totalsByCurrency)) {
    afterTableY += 14;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(20, 20, 20);
    doc.setFontSize(10);
    const right = pageWidth - margin;
    doc.text(`${t.count} payments • ${t.hours.toFixed(2)} hours`, margin, afterTableY);
    doc.text(`Gross  ${fmtMoneyMinor(t.gross, currency)}`, right - 250, afterTableY, { align: "left" });
    doc.text(`RCT  -${fmtMoneyMinor(t.rct, currency)}`, right - 130, afterTableY, { align: "left" });
    doc.setFont("helvetica", "bold");
    doc.text(`Net  ${fmtMoneyMinor(t.net, currency)}`, right, afterTableY, { align: "right" });
  }

  // ---- VAT reverse charge note ----
  if (inv.subcontractor.vatReverseCharge) {
    afterTableY += 28;
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(80, 80, 80);
    doc.text(
      "VAT reverse charge applies. The recipient is liable for accounting for VAT in accordance with Section 16(2) VATCA 2010.",
      margin,
      afterTableY,
      { maxWidth: pageWidth - margin * 2 },
    );
  }

  // ---- Bank details footer ----
  if (inv.bank?.iban || inv.bank?.accountNumber) {
    afterTableY += 30;
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(80, 80, 80);
    doc.text("PAYMENT DETAILS", margin, afterTableY);
    afterTableY += 13;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(20, 20, 20);
    doc.setFontSize(10);
    if (inv.bank.bankName)          { doc.text(`Bank:        ${inv.bank.bankName}`,          margin, afterTableY); afterTableY += 13; }
    if (inv.bank.accountHolderName) { doc.text(`Account:     ${inv.bank.accountHolderName}`, margin, afterTableY); afterTableY += 13; }
    if (inv.bank.iban)              { doc.text(`IBAN:        ${inv.bank.iban}`,              margin, afterTableY); afterTableY += 13; }
    if (inv.bank.bic)               { doc.text(`BIC/SWIFT:   ${inv.bank.bic}`,               margin, afterTableY); afterTableY += 13; }
  }

  // ---- Footer ----
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  doc.text(
    `${brandName} · self-billing record · not affiliated with the Revenue Commissioners`,
    pageWidth / 2,
    pageHeight - 24,
    { align: "center" },
  );

  return doc;
}

export function downloadInvoicePdf(inv: InvoicePayload, brandName?: string): void {
  const doc = generateInvoicePdf(inv, brandName);
  const subName = inv.subcontractor.fullName?.replace(/\s+/g, "_") || inv.subcontractor.id.slice(0, 6);
  const filename = `${inv.invoiceNumber}_${subName}.pdf`;
  doc.save(filename);
}

export function invoiceMailto(inv: InvoicePayload, brandName = "Samwise"): string {
  const to = inv.accountantEmail || "";
  const subject = `Self-billing invoice ${inv.invoiceNumber} — ${inv.subcontractor.fullName || ""}`;
  const totalsLine = Object.entries(inv.totalsByCurrency)
    .map(([c, t]) => `${c} ${(t.gross / 100).toFixed(2)} gross / ${(t.rct / 100).toFixed(2)} RCT / ${(t.net / 100).toFixed(2)} net`)
    .join(" • ");
  const body = [
    "Hi,",
    "",
    `Please find the self-billing invoice ${inv.invoiceNumber} for ${inv.subcontractor.fullName || ""} attached.`,
    "",
    `Period: ${inv.period.from} → ${inv.period.to}`,
    `Totals: ${totalsLine}`,
    "",
    "Generated by " + brandName + ".",
  ].join("\n");
  return `mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}
